name: Build and Deploy Lambda

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20  # Specify the Go version

      # Step 3: Build the Lambda binary
      - name: Build Lambda binary
        run: |
          mkdir -p lambda_build
          cd lambda_build
          git clone https://github.com/YOUR_GITHUB_USERNAME/iss-telemetry-analyzer.git
          cd iss-telemetry-analyzer
          GOOS=linux GOARCH=amd64 go build -o main
          zip ../iss-telemetry-analyzer.zip main

      # Step 4: Upload the package to S3
      - name: Upload to S3
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Lambda package
        run: |
          aws s3 cp lambda_build/iss-telemetry-analyzer.zip s3://iss-telemetry-analyzer-lambda/iss-telemetry-analyzer.zip